#
# Makefile for building the SNS2 module as part of the kernel tree.
#

obj-$(CONFIG_SECURITY_NETWORK_SOCKMON) := acheron.o

acheron-y := communication.o display_debug.o hook_bind.o hook_connect.o init.o notification_buffer.o statistics.o exec_resolve.o

